### ISSUE TITLE
java.lang.ClassNotFoundException: oracle.cloud.connector.api.CloudApplicationConnectionFactory

### ISSUE THREAD

**Issue by jiehuaou** [ninckblokje/MongoDBCloudAdapter#1]
build the adapter package with your source code , and deploy to my jdev environment according to your guide,

the result is :
1) I can see the mongoDb adapter at jdev component panel,
2) I can drag it into the right side of my composite,
3) I can fill data in the connection and operation steps,
4) But in the summary step, when I click "finish", an exception arise:

Caused by:
java.lang.ClassNotFoundException: oracle.cloud.connector.api.CloudApplicationConnectionFactory
  org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
  org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
  org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
  org.netbeans.modules.netbinox.NetbinoxLoader.loadClass(NetbinoxLoader.java:97)
  j.lang.ClassLoader.loadClass(ClassLoader.java:358)
  j.lang.ClassLoader.defineClass1(Native Method)
  j.lang.ClassLoader.defineClass(ClassLoader.java:800)
  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
  org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:632)
  org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:607)
  org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:568)
  org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:492)
  org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:465)
  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
  org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
  org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
  org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
  org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
  org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
  org.netbeans.modules.netbinox.NetbinoxLoader.loadClass(NetbinoxLoader.java:97)
  j.lang.ClassLoader.loadClass(ClassLoader.java:358)
  nl.syntouch.oracle.adapter.cloud.mongodb.plugin.generator.MongoDBMetadataGenerator.initializeContext(MongoDBMetadataGenerator.java:61)
  o.tip.tools.ide.adapters.cloud.impl.generation.AbstractRuntimeMetadataGenerator.generate(AbstractRuntimeMetadataGenerator.java:120)
  o.tip.tools.adapters.cloud.impl.AbstractCloudAdapterUIBinding.generateMetadataArtifacts(AbstractCloudAdapterUIBinding.java:242)
  o.tip.tools.ide.portablewizard.controller.WizardControllerAbstract.create(WizardControllerAbstract.java:1073)
  o.tip.tools.ide.portablewizard.controller.WizardControllerAbstract.wizardFinished(WizardControllerAbstract.java:1006)
  o.bali.ewt.wizard.BaseWizard.processWizardEvent(BaseWizard.java:2540)
  o.bali.ewt.wizard.BaseWizard.processEventImpl(BaseWizard.java:2587)
  o.bali.ewt.LWComponent.processEvent(LWComponent.java:658)
  o.bali.ewt.wizard.BaseWizard.doFinish(BaseWizard.java:2186)
  o.bali.ewt.wizard.BaseWizard$Action$1.run(BaseWizard.java:4029)
  j.a.event.InvocationEvent.dispatch(InvocationEvent.java:312)
  j.a.EventQueue.dispatchEventImpl(EventQueue.java:745)
  j.a.EventQueue.access$300(EventQueue.java:103)
  j.a.EventQueue$3.run(EventQueue.java:706)
  j.a.EventQueue$3.run(EventQueue.java:704)
  j.security.AccessController.doPrivileged(Native Method)
  j.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  j.a.EventQueue.dispatchEvent(EventQueue.java:715)
  o.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)
  o.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)
  j.a.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  j.a.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  j.a.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
  j.a.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
  j.a.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
  j.security.AccessController.doPrivileged(Native Method)
  j.a.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
  j.a.Dialog.show(Dialog.java:1082)
  j.a.Component.show(Component.java:1655)
  j.a.Component.setVisible(Component.java:1607)
  j.a.Window.setVisible(Window.java:1014)
  j.a.Dialog.setVisible(Dialog.java:1005)
  o.bali.ewt.wizard.WizardDialog.runDialog(WizardDialog.java:382)
  o.bali.ewt.wizard.WizardDialog.runDialog(WizardDialog.java:298)
  o.tip.tools.ide.portablewizard.controller.WizardController.displayDialog(WizardController.java:85)
  nl.syntouch.oracle.adapter.cloud.mongodb.wizard.MongoDBJcaEndpoint.runCreateWizard(MongoDBJcaEndpoint.java:45)
  o.tip.tools.ide.fabric.api.SCAEndpointAbstract.createEndpoint(SCAEndpointAbstract.java:71)
  o.tip.tools.ide.fabric.gui.controller.ActionExternalReferenceEdit.add(ActionExternalReferenceEdit.java:195)
  o.tip.tools.ide.fabric.gui.controller.ActionExternalReferenceEdit.process(ActionExternalReferenceEdit.java:152)
  o.tip.tools.ide.fabric.gui.controller.DiagramController.processActionRequest(DiagramController.java:358)
  o.tip.tools.ide.fabric.gui.components.ManagerView$1.run(ManagerView.java:692)
  j.a.event.InvocationEvent.dispatch(InvocationEvent.java:312)
  j.a.EventQueue.dispatchEventImpl(EventQueue.java:745)
  j.a.EventQueue.access$300(EventQueue.java:103)
  j.a.EventQueue$3.run(EventQueue.java:706)
  j.a.EventQueue$3.run(EventQueue.java:704)
  j.security.AccessController.doPrivileged(Native Method)
  j.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  j.a.EventQueue.dispatchEvent(EventQueue.java:715)
  o.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)
  o.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)
  j.a.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  j.a.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  j.a.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  j.a.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  j.a.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  j.a.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by ninckblokje** [comment]
Hi,

When did you download the sources? I thought I pushed a fix for this issue.

Jeroen

**Comment by ninckblokje** [comment]
I believe I fixed it (see previous comment), so I am closing this issue.
